"""Request / response schemas. The response carries the Responsible AI metadata so every decision is traceable."""
from pydantic import BaseModel, Field, field_validator


class ChatRequest(BaseModel):
    question: str = Field(min_length=1, max_length=2000)

    @field_validator("question")
    @classmethod
    def not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("question must not be blank")
        return v.strip()


class Source(BaseModel):
    id: str
    title: str
    category: str = ""
    relevance: float = 0.0


class ChatResponse(BaseModel):
    answer: str
    sources: list[Source] = []
    query_type: str                       # INCIDENT | KNOWLEDGE | GENERAL | OUT_OF_SCOPE
    grounded: bool                        # answer is supported by retrieved enterprise documents
    grounding_score: float                # application-level retrieval-match metric (0..1), NOT validated truth
    risk_level: str                       # LOW | MEDIUM | HIGH | CRITICAL (portfolio demonstration classification)
    human_review_required: bool
    human_review_reasons: list[str] = []
    safety_flags: list[str] = []
    conflict_detected: bool = False
    refused: bool = False
    privacy_notice: str = ""
    ai_disclosure: bool = True
    ai_disclosure_text: str = "This response was generated by AI using enterprise knowledge sources."
    risk_classification_note: str = "Portfolio demonstration risk classification"
    explanation: str = ""                 # plain-language summary of how the answer was produced (no chain-of-thought)
    tokens_used: int = 0


class SafetyCheckRequest(BaseModel):
    text: str = Field(min_length=1, max_length=2000)


class SafetyCheckResponse(BaseModel):
    safe: bool
    blocked: bool
    flags: list[str]
    details: list[str]
    checkers_used: list[str]
