"""Multi-agent pipeline: Orchestrator -> worker agents -> Responsible AI Review -> final response.

Agents run one after another (simple and predictable). Independent agents could run in parallel later to cut latency.
"""
import logging

from app.agents import general_agent, incident_agent, knowledge_agent, orchestrator, responsible_ai_agent
from app.agents.messages import AgentMessage, OrchestratorPlan, ReviewVerdict, TraceStep
from app.models import ChatResponse, Source
from app.responsible_ai import OUT_OF_SCOPE_MSG, PRIVACY_NOTICE, _refusal_text
from app.safety import SafetyChecker, redact

log = logging.getLogger("multi-agent")

WORKERS = {"incident_agent": incident_agent, "knowledge_agent": knowledge_agent, "general_agent": general_agent}
PURPOSE = {
    "orchestrator": "Understand the request and choose the agents",
    "incident_agent": "Analyse the incident using runbooks and past incidents",
    "knowledge_agent": "Retrieve enterprise policy and procedure knowledge",
    "general_agent": "Answer a general technology question (no enterprise sources)",
    "responsible_ai_agent": "Review grounding, safety, risk, privacy and human oversight",
}
BASIS_LABEL = {"KNOWN_FROM_SOURCES": "From sources", "INFERENCE": "Inference", "UNKNOWN": "Unknown"}
SECTION = {"incident_agent": "Incident analysis", "knowledge_agent": "Policy and knowledge", "general_agent": "General knowledge"}
WITHHELD = "I can't share that content. Please ask an enterprise IT question."


def _render(messages: list[AgentMessage]) -> str:
    parts = []
    for m in messages:
        if m.agent == "incident_agent" and m.status == "success":
            body = "\n".join(f"- *{BASIS_LABEL[f.basis]}:* {f.text}" for f in m.findings)
        else:
            body = "\n\n".join(f.text for f in m.findings)
        parts.append(f"**{SECTION[m.agent]}**\n\n{body}" if len(messages) > 1 else body)
    return "\n\n".join(parts)


def _trace(plan: OrchestratorPlan, messages: list[AgentMessage], verdict: ReviewVerdict) -> list[TraceStep]:
    route = ", ".join(plan.agents) if plan.agents else ("blocked by safety rules" if plan.blocked else "no agent needed")
    steps = [TraceStep(agent="orchestrator", status="done", purpose=PURPOSE["orchestrator"], result=f"Routed to: {route}")]
    for m in messages:
        steps.append(TraceStep(agent=m.agent, status=m.status, purpose=PURPOSE[m.agent], result=m.summary))
    steps.append(TraceStep(
        agent="responsible_ai_agent", status="approved" if verdict.approved else "human_review" if verdict.human_review_required else "done",
        purpose=PURPOSE["responsible_ai_agent"], result=f"Risk {verdict.risk_level}. {verdict.reason}"[:300],
    ))
    return steps


def handle(question: str, checker: SafetyChecker | None = None) -> ChatResponse:
    safe_question = redact(question)  # nothing credential-like goes to any agent, model or log
    plan = orchestrator.plan(safe_question)
    messages = [WORKERS[name].run(safe_question) for name in plan.agents]
    verdict = responsible_ai_agent.review(safe_question, plan, messages, checker)
    flags = verdict.safety_flags
    withheld = any(f.startswith("OUTPUT_") for f in flags)

    sources: dict[str, Source] = {}
    for m in messages:
        for s in m.sources:
            sources.setdefault(s.id, Source(**s.model_dump()))

    refused = False
    query_type = plan.query_types[0] if plan.query_types else "OUT_OF_SCOPE"
    if verdict.blocked or not messages:  # stopped by rules, or the orchestrator found no agent that fits
        answer = _refusal_text(flags) if verdict.blocked else OUT_OF_SCOPE_MSG
        refused, query_type, sources = True, "OUT_OF_SCOPE", {}
        explanation = "The request was stopped or judged out of scope before any enterprise search or model answer."
    elif withheld:
        answer, sources = WITHHELD, {}
        explanation = "The generated answer was withheld by the Responsible AI review."
    else:
        answer = _render(messages)
        explanation = f"Orchestrator routed the request to {', '.join(plan.agents)}; the Responsible AI agent reviewed the combined result."

    if verdict.human_review_required and not refused:
        answer = answer.rstrip() + "\n\n**Human review recommended.**"

    enterprise = [m for m in messages if m.agent != "general_agent"]
    score = min((m.grounding_score for m in enterprise), default=0.0)
    if sources:
        disclosure = "This response was generated by AI using enterprise knowledge sources."
    elif plan.query_types == ["GENERAL"] and not refused:
        disclosure = "This response was generated by AI from general knowledge. No enterprise knowledge sources were used."
    else:
        disclosure = "This response was generated by AI. No enterprise knowledge sources were used."
    notice = PRIVACY_NOTICE if {"SENSITIVE_DATA_IN_INPUT", "CREDENTIAL_REQUEST"} & set(flags) else ""
    tokens = plan.tokens + sum(m.tokens for m in messages) + verdict.tokens

    agents_used = ["orchestrator"] + [m.agent for m in messages] + ["responsible_ai_agent"]
    log.info(  # safe telemetry only: no question text, no answer text
        "multi-agent agents=%s risk=%s grounded=%s review=%s flags=%s sources=%d tokens=%d",
        agents_used, verdict.risk_level, verdict.grounded, verdict.human_review_required, flags, len(sources), tokens,
    )
    return ChatResponse(
        answer=answer,
        sources=list(sources.values()),
        query_type=query_type,
        grounded=verdict.grounded and not refused,
        grounding_score=round(score, 2),
        risk_level=verdict.risk_level,
        human_review_required=verdict.human_review_required,
        human_review_reasons=verdict.human_review_reasons,
        safety_flags=flags,
        conflict_detected=any(m.conflict_detected for m in messages),
        refused=refused,
        privacy_notice=notice,
        ai_disclosure_text=disclosure,
        explanation=explanation,
        tokens_used=tokens,
        agents_used=agents_used,
        agent_trace=_trace(plan, messages, verdict),
        review_reason=verdict.reason,
    )
